expense_expense:
    resource: "@ExpenseBundle/Resources/config/routing/expense.yml"
    prefix:   /expense

expense_home:
    path:     /expense/home
    defaults: { _controller: ExpenseBundle:Default:index }

api_expense:
    path:     /api/v1/expense
    defaults: { _controller: ExpenseBundle:Api:index }
